### ISSUE TITLE
Template QoL updates

### ISSUE THREAD

**Issue by ignatovv** [anytypeio/roadmap#30]
- Add an ability to edit and open templates from sets and collections
- Add an ability to apply template to already existed object
- etc.

**Comment by isle9** [comment]
What's the priority on being able to filter on the template used to create the object, when setting up a filter in a set?
This would be very useful for inline sets in templates since you would be able to automatically create filters for that object.
Use cases like linking your tasks to your projects would benefit a lot from this improvement, since you wouldn't need to set up your inline sets manually every time anymore.

Related:
https://community.anytype.io/t/allow-set-to-filter-on-template-used-to-create-object/7827
https://community.anytype.io/t/add-a-feature-to-reference-the-current-object-in-inline-sets/8721

**Comment by ignatovv** [comment]
@isle9 not really any priority at the moment

**Comment by larrydewey** [comment]
Any chance that the macro features might be included in the scope here? By macro features, I am referring to template place-holders like `{{date}}` or `{{user}}` which will populate on creation with the information of the current date or user.

**Comment by ignatovv** [comment]
> Any chance that the macro features might be included in the scope here? By macro features, I am referring to template place-holders like `{{date}}` or `{{user}}` which will populate on creation with the information of the current date or user.

Hi @larrydewey, it seems that relations and mentions should cover your needs. You can mention humans or dates directly in templates, and relations also can be placed on the canvas.

**Comment by larrydewey** [comment]
That is not entirely accurate @ignatovv. Instead of mentioned a specific date, in my use-case I would want to place the `{{date}}` in the name of the template to be filled upon creation. I am manually entering this information right now.

**Comment by superpupervlad** [comment]
@ignatovv Object creation with "Turn into object" button still create object with blank template rather than default. I don't think this is expected behavior 
v0.35.25-beta
