### ISSUE TITLE
Copy/paste between Spaces

### ISSUE THREAD

**Issue by charlotte-chiang** [anytypeio/roadmap#39]

**Comment by ubrandes** [comment]
Thanks for picking this up! I've suggested a few use cases and the additional capability to copy objects between spaces in [this community forum post](https://community.anytype.io/t/linking-between-spaces/12573/2?u=ubr).

**Comment by poweredupbass** [comment]
This is going to be a game changer!! I was just diving into PKM frameworks and worried about breaking my second brain out to 3 different spaces but not having them connected would be a no go. This will give me that separation and connection that I selectively need! Thanks so much for picking this up! I'm stoked to see this come through! Go AnyTeam! ⚡⚡

**Comment by rushthomas** [comment]
Seeing that the title was changed from "Links & Relations between Spaces" to "Copy/paste between Spaces" is a bummer though - assuming that links between spaces is getting pushed out. Is that accurate?

**Comment by Adda0** [comment]
I see it the same as @rushthomas. Both linking (links and relations) between spaces and easier moving of objects between spaces (copying/pasting) is necessary for spaces to be of use to many of us. However, these are two entirely distinct, if related, features. How should we interpret this change of the name of this issue? Is linking between spaces still planned, just not for now? Is copying/pasting supposed to completely replace the original linking between spaces and linking is no longer planned? Which Any Requests, if any, do you relate to copying/pasting between spaces ([Allow copying types, relations and templates between spaces](https://community.anytype.io/t/allow-copying-types-relations-and-templates-between-spaces/20649), Any Help [Is it possible to transfer things between spaces?](https://community.anytype.io/t/is-it-possible-to-transfer-things-between-spaces/12234/)?) and linking between spaces ([Linking between Spaces](https://community.anytype.io/t/linking-between-spaces/12573)?) so that I can add the vote for the linking if linking is not coming in the next Q?

**Comment by krislmo** [comment]
I am also wondering the same as @rushthomas and @Adda0. I agree that both linking and copying are crucial and would love an update on this. I signed up as a co-creator anticipating the linking between spaces!

**Comment by RichardCapricorn** [comment]
My views are in line with @rushthomas @Adda0 @krislmo .
One of the main reasons I gained the co-creator plan was to use Family Space with my family, and in our workflow we copy a portion of the photos, book reviews and other objects created in our own private spaces to our Family Space. 
So we're looking forward to this feature, too.

**Comment by A-Z-X-R** [comment]
Any updates regarding this feature? We are in Q3 of 2024
